modLoader="javafml"
loaderVersion="[33,)"
license="GPLv3"
issueTrackerURL="https://github.com/CorgiTaco/ShutupExperimentalSettings/issues"
[[mods]]
modId="shutupexperimentalsettings"
version="1.0.0"
displayName="Shutup Experimental Settings!"
displayURL="https://github.com/CorgiTaco/ShutupExperimentalSettings"
logoFile="logo_text.png"
credits="RdvDev2 for the code from fabric"
authors="Corgi Taco & RdvDev2"
description='''
Turns off the annoying experimental settings prompt before creating a world.
'''
[[dependencies.shutupexperimentalsettings]]
    modId="forge"
    mandatory=true
    versionRange="[33.0.0,)"
    ordering="NONE"
    side="BOTH"